{
 "title": "SOAC Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "target",
    "label": "Sensor",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"http://ec2-44-229-131-224.us-west-2.compute.amazonaws.com:8080/UI_Sandpoint_Organic_Ag_Center.png\" width=\"100%\">"
   }
  },
  {
   "title": "Orchard Images",
   "type": "text",
   "gridPos": { "h": 12, "w": 8, "x": 7, "y": 0 },
   "options": {
    "content": "<img src=\"http://ec2-44-229-131-224.us-west-2.compute.amazonaws.com:8080/gateway.jpg\" width=\"100%\">\r\n"
   }
  },
  {
   "title": "Gateway Location",
   "type": "geomap",
   "gridPos": { "h": 7, "w": 7, "x": 15, "y": 0 },
   "targets": [
    {
     "collection": "renogy_solar_charger_instances",
     "queryLanguage": "json",
     "queryText": "[\n  {\n    \"$match\": {}\n  }\n]"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "collection": "renogy_solar_charger",
     "queryLanguage": "json",
     "queryText": "[\n        {\n            \"$group\": {\n                \"_id\": \"$time\",\n                \"batt\": {\n                    \"$avg\":\"$battery_percentage\"\n                },\n                \"time\": {\n                    \"$first\": \"$time\"\n                }\n            }\n        },\n        \n        {\n        \"$addFields\": {\n            \"time\": {\n                \"$dateFromString\": {\n                    \"dateString\": \"$time\"\n                }\n            }\n        }\n    },\n    {\n        \"$match\": {\n            \"$expr\": {\n                \"$and\": [\n                    {\n                        \"$gte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__from}\"\n                                }\n                            }\n                        ]\n                    },\n                    {\n                        \"$lte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__to}\"\n                                }\n                            }\n                        ]\n                    }\n                ]\n            }\n        }\n    },\n        {\n            \"$sort\": {\n                \"time\": -1\n            }\n        },\n        {\n            \"$project\": {\n                \"_id\": 0,\n                \"time\": 1,\n                \"batt\": \"$batt\"\n            }\n        }\n    ]"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "collection": "renogy_solar_charger",
     "queryLanguage": "json",
     "queryText": "[\n    {\n        \"$addFields\": {\n            \"timestamp\": {\n                \"$toDate\": \"$timestamp\"\n            }\n        }\n    },\n    {\n        \"$project\": {\n            \"_id\": 0,\n            \"timestamp\": 1,\n            \"batterylow\": { \n                \"$cond\": {\n                    \"if\": { \"$eq\": [\"$batterylow\", \"deactivated\"] },\n                    \"then\": 0,\n                    \"else\": {\n                        \"$cond\": {\n                            \"if\": { \"$eq\": [\"$batterylow\", \"floating\"] },\n                            \"then\": 1,\n                            \"else\": 2\n                        }\n                    }\n                }\n            }\n        }\n    }\n]"
    }
   ]
  },
  {
   "title": "All Weather Rack Data Points",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
   "targets": [
    {
     "collection": "weather_rack",
     "queryLanguage": "json",
     "queryText": "[\n    {\n        \"$match\": {\n            \"device\": 12\n        }\n    },\n    {\n        \"$addFields\": {\n            \"time\": {\n                \"$dateFromString\": {\n                    \"dateString\": \"$time\"\n                }\n            }\n        }\n    },\n{\n        \"$match\": {\n            \"$expr\": {\n                \"$and\": [\n                    {\n                        \"$gte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__from}\"\n                                }\n                            }\n                        ]\n                    },\n                    {\n                        \"$lte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__to}\"\n                                }\n                            }\n                        ]\n                    }\n                ]\n            }\n        }\n    },\n    {\n        \"$sort\": {\n            \"time\": -1\n        }\n    }\n    \n]"
    }
   ]
  },
  {
   "title": "Internal Pi (F)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "collection": "gateway_stats",
     "queryLanguage": "json",
     "queryText": "[\n  {\n    \"$group\": {\n      \"_id\": \"$time\",\n      \"temp\": {\n        \"$avg\": \"$internal_temp\"\n      },\n      \"time\": {\n        \"$first\": \"$time\"\n      }\n    }\n  },\n  {\n    \"$addFields\": {\n      \"time\": {\n        \"$dateFromString\": {\n          \"dateString\": \"$time\"\n        }\n      }\n    }\n  },\n  {\n    \"$match\": {\n      \"$expr\": {\n        \"$and\": [\n          {\n            \"$gte\": [\n              \"$time\",\n              {\n                \"$toDate\": {\n                  \"$toLong\": \"${__from}\"\n                }\n              }\n            ]\n          },\n          {\n            \"$lte\": [\n              \"$time\",\n              {\n                \"$toDate\": {\n                  \"$toLong\": \"${__to}\"\n                }\n              }\n            ]\n          }\n        ]\n      }\n    }\n  },\n  {\n    \"$sort\": {\n      \"time\": -1\n    }\n  },\n  {\n    \"$addFields\": {\n      \"temperatureF\": {\n        \"$add\": [\n          {\n            \"$multiply\": [\n              \"$temp\",\n              1.8\n            ]\n          },\n          32\n        ]\n      }\n    }\n  },\n  {\n    \"$project\": {\n      \"_id\": 0,\n      \"time\": 1,\n      \"temperatureF\": \"$temperatureF\"\n    }\n  }\n]"
    }
   ]
  },
  {
   "title": "Internal Pi (C)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "collection": "gateway_stats",
     "queryLanguage": "json",
     "queryText": "[\n        {\n            \"$group\": {\n                \"_id\": \"$time\",\n                \"temp\": {\n                    \"$avg\":\"$internal_temp\"\n                },\n                \"time\": {\n                    \"$first\": \"$time\"\n                }\n            }\n        },\n        {\n            \"$addFields\": {\n                \"time\": {\n                    \"$dateFromString\": {\n                        \"dateString\": \"$time\"\n                    }\n                }\n            }\n        },\n        {\n        \"$match\": {\n            \"$expr\": {\n                \"$and\": [\n                    {\n                        \"$gte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__from}\"\n                                }\n                            }\n                        ]\n                    },\n                    {\n                        \"$lte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__to}\"\n                                }\n                            }\n                        ]\n                    }\n                ]\n            }\n        }\n    },\n        {\n            \"$sort\": {\n                \"time\": -1\n            }\n        },\n        {\n            \"$project\": {\n                \"_id\": 0,\n                \"time\": 1,\n                \"temp\": \"$temp\"\n            }\n        }\n    ]"
    }
   ]
  },
  {
   "title": "Internal Fans",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "collection": "gateway_stats",
     "queryLanguage": "json",
     "queryText": "[\n        {\n            \"$group\": {\n                \"_id\": \"$time\",\n                \"temp\": {\n                    \"$avg\":\"$internal_temp\"\n                },\n                \"time\": {\n                    \"$first\": \"$time\"\n                }\n            }\n        },\n        {\n            \"$addFields\": {\n                \"time\": {\n                    \"$dateFromString\": {\n                        \"dateString\": \"$time\"\n                    }\n                }\n            }\n        },\n        {\n        \"$match\": {\n            \"$expr\": {\n                \"$and\": [\n                    {\n                        \"$gte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__from}\"\n                                }\n                            }\n                        ]\n                    },\n                    {\n                        \"$lte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__to}\"\n                                }\n                            }\n                        ]\n                    }\n                ]\n            }\n        }\n    },\n        {\n            \"$sort\": {\n                \"time\": -1\n            }\n        },\n        {\n            \"$project\": {\n                \"_id\": 0,\n                \"time\": 1,\n                \"temp\": \"$temp\"\n            }\n        }\n    ]"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "collection": "gateway_stats",
     "queryLanguage": "json",
     "queryText": " [\n        {\n            \"$group\": {\n                \"_id\": \"$time\",\n                \"mem\": {\n                    \"$avg\":\"$memory_free\"\n                },\n                \"time\": {\n                    \"$first\": \"$time\"\n                }\n            }\n        },\n        \n        {\n            \"$addFields\": {\n                \"time\": {\n                    \"$dateFromString\": {\n                        \"dateString\": \"$time\"\n                    }\n                }\n            }\n        },\n        {\n        \"$match\": {\n            \"$expr\": {\n                \"$and\": [\n                    {\n                        \"$gte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__from}\"\n                                }\n                            }\n                        ]\n                    },\n                    {\n                        \"$lte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__to}\"\n                                }\n                            }\n                        ]\n                    }\n                ]\n            }\n        }\n    },\n        {\n            \"$sort\": {\n                \"time\": -1\n            }\n        },\n        {\n            \"$project\": {\n                \"_id\": 0,\n                \"time\": 1,\n                \"mem\": 1\n            }\n        }\n    ]"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "collection": "gateway_stats",
     "queryLanguage": "json",
     "queryText": "[\n    {\n        \"$group\": {\n            \"_id\": \"$time\",\n            \"cpu\": {\n                \"$avg\": \"$cpu_usage\"\n            },\n            \"time\": {\n                \"$first\": \"$time\"\n            }\n        }\n    },\n    {\n        \"$addFields\": {\n            \"time\": {\n                \"$dateFromString\": {\n                    \"dateString\": \"$time\"\n                }\n            }\n        }\n    },\n    {\n        \"$match\": {\n            \"$expr\": {\n                \"$and\": [\n                    {\n                        \"$gte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__from}\"\n                                }\n                            }\n                        ]\n                    },\n                    {\n                        \"$lte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__to}\"\n                                }\n                            }\n                        ]\n                    }\n                ]\n            }\n        }\n    },\n    {\n        \"$sort\": {\n            \"time\": -1\n        }\n    },\n    {\n        \"$project\": {\n            \"_id\": 0,\n            \"time\": 1,\n            \"cpu\": \"$cpu\"\n        }\n    }\n]"
    }
   ]
  },
  {
   "title": " Soil Volumetric Water Content",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "collection": "meter_teros10",
     "queryLanguage": "json",
     "queryText": "[\n        {\n            \"$addFields\": {\n                \"time\": {\n                    \"$dateFromString\": {\n                        \"dateString\": \"$time\"\n                    }\n                }\n            }\n        },\n        {\n        \"$match\": {\n            \"$expr\": {\n                \"$and\": [\n                    {\n                        \"$gte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__from}\"\n                                }\n                            }\n                        ]\n                    },\n                    {\n                        \"$lte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__to}\"\n                                }\n                            }\n                        ]\n                    }\n                ]\n            }\n        }\n    },\n        {\n            \"$sort\": {\n                \"time\": -1\n            }\n        },\n        {\n            \"$project\": {\n                \"_id\": \"$time\",\n                \"VWC\": 1,\n                \"VWC_RAW\":1\n            }\n        }\n    ]"
    }
   ]
  },
  { "title": "Weather Data for $target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }, "repeat": "target" },
  {
   "title": "Current (F)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "collection": "weather_rack",
     "queryLanguage": "json",
     "queryText": "[\n    {\n        \"$match\": {\n            \"label\": \"${target}\"\n        }\n    },\n    {\n        \"$group\": {\n            \"_id\": \"$time\",\n            \"temp\": {\n                \"$avg\":\"$temperature\"\n            },\n            \"time\": {\n                \"$first\": \"$time\"\n            }\n        }\n    },\n    {\n        \"$addFields\": {\n            \"time\": {\n                \"$dateFromString\": {\n                    \"dateString\": \"$time\"\n                }\n            }\n        }\n    },\n    {\n        \"$match\": {\n            \"$expr\": {\n                \"$and\": [\n                    {\n                        \"$gte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__from}\"\n                                }\n                            }\n                        ]\n                    },\n                    {\n                        \"$lte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__to}\"\n                                }\n                            }\n                        ]\n                    }\n                ]\n            }\n        }\n    },\n    {\n        \"$sort\": {\n            \"time\": -1\n        }\n    },\n    {\n        \"$addFields\": {\n        \"temperatureF\": {\n            \"$add\": [\n              { \"$multiply\": [ \"$temp\", 1.8 ] },\n              32\n            ]\n          }\n        }\n    },\n    {\n        \"$project\": {\n            \"_id\": 0,\n            \"temperatureF\": 1,\n            \"time\": 1\n        }\n    }\n]"
    }
   ]
  },
  {
   "title": "Current (C)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "collection": "weather_rack",
     "queryLanguage": "json",
     "queryText": " [\n        {\n            \"$match\": {\n                \"label\": \"${target}\"\n            }\n        },\n        {\n            \"$addFields\": {\n                \"time\": {\n                    \"$dateFromString\": {\n                        \"dateString\": \"$time\"\n                    }\n                }\n            }\n        },\n        {\n        \"$match\": {\n            \"$expr\": {\n                \"$and\": [\n                    {\n                        \"$gte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__from}\"\n                                }\n                            }\n                        ]\n                    },\n                    {\n                        \"$lte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__to}\"\n                                }\n                            }\n                        ]\n                    }\n                ]\n            }\n        }\n    },\n        {\n            \"$sort\": {\n                \"time\": -1\n            }\n        },\n        {\n            \"$project\": {\n                \"_id\": \"$time\",\n                \"temperature\": 1\n            }\n        }\n    ]"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "collection": "weather_rack",
     "queryLanguage": "json",
     "queryText": "[\n    {\n        \"$match\": {\n            \"label\": \"${target}\"\n        }\n    },\n    {\n        \"$group\": {\n            \"_id\": \"$time\",\n            \"time\": {\n                \"$first\": \"$time\"\n            },\n            \"humidity\": {\n                \"$avg\":\"$humidity\"\n            }\n        }\n    },\n    {\n        \"$addFields\": {\n            \"time\": {\n                \"$dateFromString\": {\n                    \"dateString\": \"$time\"\n                }\n            }\n        }\n    },\n    {\n        \"$match\": {\n            \"$expr\": {\n                \"$and\": [\n                    {\n                        \"$gte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__from}\"\n                                }\n                            }\n                        ]\n                    },\n                    {\n                        \"$lte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__to}\"\n                                }\n                            }\n                        ]\n                    }\n                ]\n            }\n        }\n    },\n    {\n        \"$sort\": {\n            \"time\": -1\n        }\n    },\n    \n    {\n        \"$project\": {\n            \"_id\": 0,\n            \"time\": 1,\n            \"humidity\": 1\n        }\n    }\n]"
    }
   ]
  },
  {
   "title": "Cumulative Rain",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "lengthin" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "collection": "weather_rack",
     "queryLanguage": "json",
     "queryText": "[\n        {\n            \"$match\": {\n                \"label\": \"${target}\"\n            }\n        },\n        {\n            \"$group\": {\n                \"_id\": \"$time\",\n                \"time\": {\n                    \"$first\": \"$time\"\n                },\n                \"rain\": {\n                    \"$avg\": \"$cumulativerain\"\n                }\n            }\n        },\n        {\n            \"$addFields\": {\n                \"time\": {\n                    \"$dateFromString\": {\n                        \"dateString\": \"$time\"\n                    }\n                }\n            }\n        },\n        {\n        \"$match\": {\n            \"$expr\": {\n                \"$and\": [\n                    {\n                        \"$gte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__from}\"\n                                }\n                            }\n                        ]\n                    },\n                    {\n                        \"$lte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__to}\"\n                                }\n                            }\n                        ]\n                    }\n                ]\n            }\n        }\n    },\n        {\n            \"$sort\": {\n                \"time\": -1\n            }\n        },\n        {\n            \"$addFields\": {\n                \"rainIn\": {\n                    \"$divide\": [\"$rain\",25.4]\n                }\n            }\n        },\n        {\n            \"$limit\": 1\n        },\n        {\n            \"$project\": {\n                \"_id\": 0,\n                \"rainIn\": 1\n            }\n        }\n    ]"
    }
   ]
  },
  {
   "title": "Station: $target",
   "type": "text",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 13 },
   "options": {
    "content": "<img src=\"http://ec2-44-229-131-224.us-west-2.compute.amazonaws.com:8080/$target.jpg\" width=\"100%\">"
   }
  },
  {
   "title": "Battery",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "collection": "weather_rack",
     "queryLanguage": "json",
     "queryText": "[\n    {\n        \"$match\": {\n            \"label\": \"${target}\"\n        }\n    },\n    {\n        \"$group\": {\n            \"_id\": \"$time\",\n            \"⚡\": {\n                \"$avg\":\"$batterylow\"\n            },\n            \"time\": {\n                \"$first\": \"$time\"\n            }\n        }\n    },\n    {\n        \"$addFields\": {\n            \"time\": {\n                \"$dateFromString\": {\n                    \"dateString\": \"$time\"\n                }\n            }\n        }\n    },\n    {\n        \"$match\": {\n            \"$expr\": {\n                \"$and\": [\n                    {\n                        \"$gte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__from}\"\n                                }\n                            }\n                        ]\n                    },\n                    {\n                        \"$lte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__to}\"\n                                }\n                            }\n                        ]\n                    }\n                ]\n            }\n        }\n    },\n    {\n        \"$sort\": {\n            \"time\": -1\n        }\n    },\n    {\n        \"$project\": {\n            \"_id\": 0,\n            \"time\": 1,\n            \"⚡\": \"$⚡\"\n        }\n    }\n]"
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "collection": "weather_rack",
     "queryLanguage": "json",
     "queryText": "[\n    {\n        \"$match\": {\n            \"label\": \"${target}\"\n        }\n    },\n    {\n        \"$group\": {\n            \"_id\": \"$time\",\n            \"time\": {\n                \"$first\": \"$time\"\n            },\n            \"windDir\": {\n                \"$avg\": \"$winddirection\"\n            }\n        }\n    },\n    {\n        \"$addFields\": {\n            \"time\": {\n                \"$dateFromString\": {\n                    \"dateString\": \"$time\"\n                }\n            }\n        }\n    },\n    {\n        \"$match\": {\n            \"$expr\": {\n                \"$and\": [\n                    {\n                        \"$gte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__from}\"\n                                }\n                            }\n                        ]\n                    },\n                    {\n                        \"$lte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__to}\"\n                                }\n                            }\n                        ]\n                    }\n                ]\n            }\n        }\n    },\n    {\n        \"$sort\": {\n            \"time\": -1\n        }\n    },\n    {\n        \"$limit\": 1\n    },\n    {\n        \"$project\": {\n            \"_id\": 0,\n            \"windDir\": 1\n        }\n    }\n]"
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "collection": "weather_rack",
     "queryLanguage": "json",
     "queryText": "[\n    {\n        \"$match\": {\n            \"label\": \"${target}\"\n        }\n    },\n    {\n        \"$group\": {\n            \"_id\": \"$time\",\n            \"time\": {\n                \"$first\": \"$time\"\n            },\n            \"uv\": {\n                \"$avg\":\"$uv\"\n            }\n        }\n    },\n    {\n        \"$addFields\": {\n            \"time\": {\n                \"$dateFromString\": {\n                    \"dateString\": \"$time\"\n                }\n            }\n        }\n    },\n    {\n        \"$match\": {\n            \"$expr\": {\n                \"$and\": [\n                    {\n                        \"$gte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__from}\"\n                                }\n                            }\n                        ]\n                    },\n                    {\n                        \"$lte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__to}\"\n                                }\n                            }\n                        ]\n                    }\n                ]\n            }\n        }\n    },\n    {\n        \"$sort\": {\n            \"time\": -1\n        }\n    },\n    {\n        \"$project\": {\n            \"_id\": 0,\n            \"time\": 1,\n            \"uv\": 1\n        }\n    }\n]"
    }
   ]
  },
  {
   "title": "Light",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "collection": "weather_rack",
     "queryLanguage": "json",
     "queryText": "[\n    {\n        \"$match\": {\n            \"label\": \"${target}\"\n        }\n    },\n    {\n        \"$group\": {\n            \"_id\": \"$time\",\n            \"time\": {\n                \"$first\": \"$time\"\n            },\n            \"lux\": {\n                \"$avg\":\"$light\"\n            }\n        }\n    },\n    {\n        \"$addFields\": {\n            \"time\": {\n                \"$dateFromString\": {\n                    \"dateString\": \"$time\"\n                }\n            }\n        }\n    },\n    {\n        \"$match\": {\n            \"$expr\": {\n                \"$and\": [\n                    {\n                        \"$gte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__from}\"\n                                }\n                            }\n                        ]\n                    },\n                    {\n                        \"$lte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__to}\"\n                                }\n                            }\n                        ]\n                    }\n                ]\n            }\n        }\n    },\n    {\n        \"$sort\": {\n            \"time\": -1\n        }\n    },\n    {\n        \"$project\": {\n            \"_id\": 0,\n            \"time\": 1,\n            \"lux\": 1\n        }\n    }\n]"
    }
   ]
  },
  {
   "title": "$target Location",
   "type": "geomap",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "collection": "weather_rack_instances",
     "queryLanguage": "json",
     "queryText": "[\n    {\n        \"$match\": {\n            \"instance_unique_identifier\": \"${target}\"\n        }\n    }\n]"
    }
   ]
  },
  {
   "title": "Average Windspeed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "collection": "weather_rack",
     "queryLanguage": "json",
     "queryText": "[\n        {\n            \"$match\": {\n                \"label\": \"${target}\"\n            }\n        },\n        {\n            \"$group\": {\n                \"_id\": \"$time\",\n                \"time\": {\n                    \"$first\": \"$time\"\n                },\n                \"wind\": {\n                    \"$avg\": \"$avewindspeed\"\n                }\n            }\n        },\n        {\n            \"$addFields\": {\n                \"time\": {\n                    \"$dateFromString\": {\n                        \"dateString\": \"$time\"\n                    }\n                }\n            }\n        },\n        {\n        \"$match\": {\n            \"$expr\": {\n                \"$and\": [\n                    {\n                        \"$gte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__from}\"\n                                }\n                            }\n                        ]\n                    },\n                    {\n                        \"$lte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__to}\"\n                                }\n                            }\n                        ]\n                    }\n                ]\n            }\n        }\n    },\n        {\n            \"$sort\": {\n                \"time\": -1\n            }\n        },\n        {\n            \"$limit\": 1\n        },\n        {\n            \"$addFields\": {\n              \"wind_mph\": { \"$multiply\": [ \"$wind\", 2.236936 ] }\n            }\n        },\n        {\n            \"$project\": {\n                \"_id\": 0,\n                \"wind_mph\": 1\n            }\n        }\n    ]"
    }
   ]
  },
  {
   "title": "Latest Wind Gust",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "collection": "weather_rack",
     "queryLanguage": "json",
     "queryText": " [\n            {\n                \"$match\": {\n                    \"label\": \"${target}\"\n                }\n            },\n            {\n                \"$group\": {\n                    \"_id\": \"$time\",\n                    \"time\": {\n                        \"$first\": \"$time\"\n                    },\n                    \"wind\": {\n                        \"$avg\": \"$gustwindspeed\"\n                    }\n                }\n            },\n            {\n                \"$addFields\": {\n                    \"time\": {\n                        \"$dateFromString\": {\n                            \"dateString\": \"$time\"\n                        }\n                    }\n                }\n            },\n            {\n        \"$match\": {\n            \"$expr\": {\n                \"$and\": [\n                    {\n                        \"$gte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__from}\"\n                                }\n                            }\n                        ]\n                    },\n                    {\n                        \"$lte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__to}\"\n                                }\n                            }\n                        ]\n                    }\n                ]\n            }\n        }\n    },\n            {\n                \"$sort\": {\n                    \"time\": -1\n                }\n            },\n            {\n                \"$limit\": 1\n            },\n            {\n                \"$addFields\": {\n                  \"wind_mph\": { \"$multiply\": [ \"$wind\", 2.236936 ] }\n                }\n            },\n            {\n                \"$project\": {\n                    \"_id\": 0,\n                    \"wind_mph\": 1\n                }\n            }\n        ]"
    }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "pressurekpa" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "collection": "bmp280",
     "queryLanguage": "json",
     "queryText": "[\n        {\n            \"$group\": {\n                \"_id\": \"$time\",\n                \"time\": {\n                    \"$first\": \"$time\"\n                },\n                \"pressure\": {\n                    \"$avg\": \"$BarometricPressure\"\n                }\n            }\n        },\n        {\n            \"$addFields\": {\n                \"time\": {\n                    \"$dateFromString\": {\n                        \"dateString\": \"$time\"\n                    }\n                }\n            }\n        },\n        {\n        \"$match\": {\n            \"$expr\": {\n                \"$and\": [\n                    {\n                        \"$gte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__from}\"\n                                }\n                            }\n                        ]\n                    },\n                    {\n                        \"$lte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__to}\"\n                                }\n                            }\n                        ]\n                    }\n                ]\n            }\n        }\n    },\n        {\n            \"$sort\": {\n                \"time\": -1\n            }\n        },\n        {\n            \"$limit\": 1\n        },\n        {\n            \"$project\": {\n                \"_id\": 0,\n                \"pressure\": 1\n            }\n        }\n    ]"
    }
   ]
  },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 23 },
   "options": {
    "content": "<img src=\"http://ec2-44-229-131-224.us-west-2.compute.amazonaws.com:8080/CSlogo.png\" width=\"100%\">\r\n<!--<img src=\"http://ec2-44-229-131-224.us-west-2.compute.amazonaws.com:8080/SCARECRO.png\" width=\"100%\">-->"
   }
  },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 23 },
   "options": {
    "content": "<!--<img src=\"http://ec2-44-229-131-224.us-west-2.compute.amazonaws.com:8080/CSlogo.png\" width=\"100%\">-->\r\n<img src=\"http://ec2-44-229-131-224.us-west-2.compute.amazonaws.com:8080/SCARECRO2.png\" width=\"100%\">"
   }
  },
  {
   "title": "Latest Reading",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "collection": "weather_rack",
     "queryLanguage": "json",
     "queryText": " [\n        {\n            \"$match\": {\n                \"label\": \"${target}\"\n            }\n        },\n        {\n            \"$addFields\": {\n                \"time\": {\n                    \"$dateFromString\": {\n                        \"dateString\": \"$time\"\n                    }\n                }\n            }\n        },\n        {\n        \"$match\": {\n            \"$expr\": {\n                \"$and\": [\n                    {\n                        \"$gte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__from}\"\n                                }\n                            }\n                        ]\n                    },\n                    {\n                        \"$lte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__to}\"\n                                }\n                            }\n                        ]\n                    }\n                ]\n            }\n        }\n    },\n        {\n            \"$sort\": {\n                \"time\": -1\n            }\n        },\n        {\n            \"$project\": {\n                \"_id\": \"$time\",\n                \"time\": 1\n            }\n        }\n    ]"
    }
   ]
  },
  { "title": "Metric Measurements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Cumulative Rain",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "collection": "weather_rack",
     "queryLanguage": "json",
     "queryText": "[\n    {\n        \"$match\": {\n            \"label\": \"${target}\"\n        }\n    },\n    {\n        \"$group\": {\n            \"_id\": \"$time\",\n            \"time\": {\n                \"$first\": \"$time\"\n            },\n            \"rain\": {\n                \"$avg\": \"$cumulativerain\"\n            }\n        }\n    },\n    {\n        \"$addFields\": {\n            \"time\": {\n                \"$dateFromString\": {\n                    \"dateString\": \"$time\"\n                }\n            }\n        }\n    },\n{\n        \"$match\": {\n            \"$expr\": {\n                \"$and\": [\n                    {\n                        \"$gte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__from}\"\n                                }\n                            }\n                        ]\n                    },\n                    {\n                        \"$lte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__to}\"\n                                }\n                            }\n                        ]\n                    }\n                ]\n            }\n        }\n    },\n    {\n        \"$sort\": {\n            \"time\": -1\n        }\n    },\n    {\n        \"$limit\": 1\n    },\n    {\n        \"$project\": {\n            \"_id\": 0,\n            \"rain\": 1,\n            \"target\": \"${target}\"\n        }\n    }\n]"
    }
   ]
  },
  {
   "title": "Average Windspeed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "collection": "weather_rack",
     "queryLanguage": "json",
     "queryText": "[\n    {\n        \"$match\": {\n            \"label\": \"${target}\"\n        }\n    },\n    {\n        \"$group\": {\n            \"_id\": \"$time\",\n            \"time\": {\n                \"$first\": \"$time\"\n            },\n            \"wind\": {\n                \"$avg\": \"$avewindspeed\"\n            }\n        }\n    },\n    {\n        \"$addFields\": {\n            \"time\": {\n                \"$dateFromString\": {\n                    \"dateString\": \"$time\"\n                }\n            }\n        }\n    },\n    {\n        \"$match\": {\n            \"$expr\": {\n                \"$and\": [\n                    {\n                        \"$gte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__from}\"\n                                }\n                            }\n                        ]\n                    },\n                    {\n                        \"$lte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__to}\"\n                                }\n                            }\n                        ]\n                    }\n                ]\n            }\n        }\n    },\n    {\n        \"$sort\": {\n            \"time\": -1\n        }\n    },\n    {\n        \"$limit\": 1\n    },\n    {\n        \"$project\": {\n            \"_id\": 0,\n            \"wind\": 1\n        }\n    }\n]"
    }
   ]
  },
  {
   "title": "Latest Wind Gust",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "collection": "weather_rack",
     "queryLanguage": "json",
     "queryText": "[\n    {\n        \"$match\": {\n            \"label\": \"${target}\"\n        }\n    },\n    {\n        \"$group\": {\n            \"_id\": \"$time\",\n            \"time\": {\n                \"$first\": \"$time\"\n            },\n            \"wind\": {\n                \"$avg\": \"$gustwindspeed\"\n            }\n        }\n    },\n    {\n        \"$addFields\": {\n            \"time\": {\n                \"$dateFromString\": {\n                    \"dateString\": \"$time\"\n                }\n            }\n        }\n    },\n    {\n        \"$match\": {\n            \"$expr\": {\n                \"$and\": [\n                    {\n                        \"$gte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__from}\"\n                                }\n                            }\n                        ]\n                    },\n                    {\n                        \"$lte\": [\n                            \"$time\",\n                            {\n                                \"$toDate\": {\n                                    \"$toLong\": \"${__to}\"\n                                }\n                            }\n                        ]\n                    }\n                ]\n            }\n        }\n    },\n    {\n        \"$sort\": {\n            \"time\": -1\n        }\n    },\n    {\n        \"$limit\": 1\n    },\n    {\n        \"$project\": {\n            \"_id\": 0,\n            \"wind\": 1\n        }\n    }\n]"
    }
   ]
  }
 ]
}