{
 "title": "SOAC Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "target",
    "label": "Sensor",
    "query": "db.weather_rack_instances.aggregate([\n            {\n                $group: { _id: \"$instance_unique_identifier\" }\n            }\n        ])"
   },
   {
    "name": "DataSource",
    "query": "grafana-mongodb-opensource-datasource"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"http://ec2-44-229-131-224.us-west-2.compute.amazonaws.com:8080/UI_Sandpoint_Organic_Ag_Center.png\" width=\"100%\">"
   }
  },
  {
   "title": "Orchard Images",
   "type": "text",
   "gridPos": { "h": 12, "w": 8, "x": 7, "y": 0 },
   "options": {
    "content": "<img src=\"http://ec2-44-229-131-224.us-west-2.compute.amazonaws.com:8080/gateway.jpg\" width=\"100%\">\r\n"
   }
  },
  {
   "title": "Gateway Location",
   "type": "geomap",
   "gridPos": { "h": 7, "w": 7, "x": 15, "y": 0 },
   "targets": [
    {
     "target": "db.renogy_solar_charger_instances.aggregate(\n[]\n)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "target": "db.renogy_solar_charger.aggregate(\n    [\n        {\n            \"$group\": {\n                \"_id\": \"$time\",\n                \"batt\": {\n                    \"$avg\":\"$battery_percentage\"\n                },\n                \"time\": {\n                    \"$first\": \"$time\"\n                }\n            }\n        },\n        {\n            // Transform 'time' from a string to a date\n            \"$addFields\": {\n                \"time\": {\n                    \"$dateFromString\": {\n                        \"dateString\": \"$time\"\n                    }\n                }\n            }\n        },\n        {\n            \"$match\": {\n                \"time\": {\n                    \"$gte\": new Date(\"${__from:date:iso}\"),\n                    \"$lte\": new Date(\"${__to:date:iso}\")\n                }\n            }\n        },\n        {\n            \"$sort\": {\n                \"time\": -1\n            }\n        },\n        \n        // Project the fields we want to keep\n        {\n            \"$project\": {\n                \"_id\": 0,\n                \"time\": 1,\n                \"batt\": \"$batt\"\n            }\n        }\n    ]\n    )",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "target": "db.renogy_solar_charger.aggregate(\n[\n    {\n        // Convert the timestamp to a date object\n        \"$set\": {\n            \"timestamp\": {\n                \"$toDate\": \"$timestamp\"\n            }\n        }\n    },\n    {\n        $project: {\n            _id: 0,\n            timestamp: 1,\n            batterylow: { // Possible values: deactivated, floating, boost\n                // Need to map to 0, 1, 2\n                $cond: {\n                    if: { $eq: [\"$batterylow\", \"deactivated\"] },\n                    then: 0,\n                    else: {\n                        $cond: {\n                            if: { $eq: [\"$batterylow\", \"floating\"] },\n                            then: 1,\n                            else: 2\n                        }\n                    }\n                }\n            }\n        }\n    }\n]\n)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "All Weather Rack Data Points",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
   "targets": [
    {
     "target": "db.weather_rack.aggregate(\n[\n    {\n        \"$match\": {\n            \"device\": 12,\n        }\n    },\n    {\n        // Transform 'time' from a string to a date\n        \"$addFields\": {\n            \"time\": {\n                \"$dateFromString\": {\n                    \"dateString\": \"$time\"\n                }\n            }\n        }\n    },\n    {\n        \"$match\": {\n            \"time\": {\n                \"$gte\": new Date(\"${__from:date:iso}\"),\n                \"$lte\": new Date(\"${__to:date:iso}\")\n            }\n        }\n    },\n    {\n        \"$sort\": {\n            \"time\": -1\n        }\n    },\n    \n]\n)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Internal Pi (F)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "target": "db.gateway_stats.aggregate(\n        [\n            {\n                \"$group\": {\n                    \"_id\": \"$time\",\n                    \"temp\": {\n                        \"$avg\":\"$internal_temp\"\n                    },\n                    \"time\": {\n                        \"$first\": \"$time\"\n                    }\n                }\n            },\n            {\n                // Transform 'time' from a string to a date\n                \"$addFields\": {\n                    \"time\": {\n                        \"$dateFromString\": {\n                            \"dateString\": \"$time\"\n                        }\n                    }\n                }\n            },\n            {\n                \"$match\": {\n                    \"time\": {\n                        \"$gte\": new Date(\"${__from:date:iso}\"),\n                        \"$lte\": new Date(\"${__to:date:iso}\")\n                    }\n                }\n            },\n            {\n                \"$sort\": {\n                    \"time\": -1\n                }\n            },\n            {\n                \"$addFields\": {\n                \"temperatureF\": {\n                    \"$add\": [\n                      { \"$multiply\": [ \"$temp\", 9/5 ] },\n                      32\n                    ]\n                  }\n                }\n            },\n            // Project the fields we want to keep\n            {\n                \"$project\": {\n                    \"_id\": 0,\n                    \"time\": 1,\n                    \"temperatureF\": \"$temperatureF\"\n                }\n            }\n        ]\n        )",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Internal Pi (C)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "target": "db.gateway_stats.aggregate(\n    [\n        {\n            \"$group\": {\n                \"_id\": \"$time\",\n                \"temp\": {\n                    \"$avg\":\"$internal_temp\"\n                },\n                \"time\": {\n                    \"$first\": \"$time\"\n                }\n            }\n        },\n        {\n            // Transform 'time' from a string to a date\n            \"$addFields\": {\n                \"time\": {\n                    \"$dateFromString\": {\n                        \"dateString\": \"$time\"\n                    }\n                }\n            }\n        },\n        {\n            \"$match\": {\n                \"time\": {\n                    \"$gte\": new Date(\"${__from:date:iso}\"),\n                    \"$lte\": new Date(\"${__to:date:iso}\")\n                }\n            }\n        },\n        {\n            \"$sort\": {\n                \"time\": -1\n            }\n        },\n        \n        // Project the fields we want to keep\n        {\n            \"$project\": {\n                \"_id\": 0,\n                \"time\": 1,\n                \"temp\": \"$temp\"\n            }\n        }\n    ]\n    )",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Internal Fans",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "target": "db.gateway_stats.aggregate(\n    [\n        {\n            \"$group\": {\n                \"_id\": \"$time\",\n                \"temp\": {\n                    \"$avg\":\"$internal_temp\"\n                },\n                \"time\": {\n                    \"$first\": \"$time\"\n                }\n            }\n        },\n        {\n            // Transform 'time' from a string to a date\n            \"$addFields\": {\n                \"time\": {\n                    \"$dateFromString\": {\n                        \"dateString\": \"$time\"\n                    }\n                }\n            }\n        },\n        {\n            \"$match\": {\n                \"time\": {\n                    \"$gte\": new Date(\"${__from:date:iso}\"),\n                    \"$lte\": new Date(\"${__to:date:iso}\")\n                }\n            }\n        },\n        {\n            \"$sort\": {\n                \"time\": -1\n            }\n        },\n        \n        // Project the fields we want to keep\n        {\n            \"$project\": {\n                \"_id\": 0,\n                \"time\": 1,\n                \"temp\": \"$temp\"\n            }\n        }\n    ]\n    )",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "target": "db.gateway_stats.aggregate(\n    [\n        {\n            \"$group\": {\n                \"_id\": \"$time\",\n                \"mem\": {\n                    \"$avg\":\"$memory_free\"\n                },\n                \"time\": {\n                    \"$first\": \"$time\"\n                }\n            }\n        },\n        {\n            // Transform 'time' from a string to a date\n            \"$addFields\": {\n                \"time\": {\n                    \"$dateFromString\": {\n                        \"dateString\": \"$time\"\n                    }\n                }\n            }\n        },\n        {\n            \"$match\": {\n                \"time\": {\n                    \"$gte\": new Date(\"${__from:date:iso}\"),\n                    \"$lte\": new Date(\"${__to:date:iso}\")\n                }\n            }\n        },\n        {\n            \"$sort\": {\n                \"time\": -1\n            }\n        },\n        // Project the fields we want to keep\n        {\n            \"$project\": {\n                \"_id\": 0,\n                \"time\": 1,\n                \"mem\": 1,\n            }\n        }\n    ]\n    )",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "target": "db.gateway_stats.aggregate(\n    [\n        {\n            \"$group\": {\n                \"_id\": \"$time\",\n                \"cpu\": {\n                    \"$avg\":\"$cpu_usage\"\n                },\n                \"time\": {\n                    \"$first\": \"$time\"\n                }\n            }\n        },\n        {\n            // Transform 'time' from a string to a date\n            \"$addFields\": {\n                \"time\": {\n                    \"$dateFromString\": {\n                        \"dateString\": \"$time\"\n                    }\n                }\n            }\n        },\n        {\n            \"$match\": {\n                \"time\": {\n                    \"$gte\": new Date(\"${__from:date:iso}\"),\n                    \"$lte\": new Date(\"${__to:date:iso}\")\n                }\n            }\n        },\n        {\n            \"$sort\": {\n                \"time\": -1\n            }\n        },\n        \n        // Project the fields we want to keep\n        {\n            \"$project\": {\n                \"_id\": 0,\n                \"time\": 1,\n                \"cpu\": \"$cpu\"\n            }\n        }\n    ]\n    )",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": " Soil Volumetric Water Content",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "target": "db.meter_teros10.aggregate(\n    [\n        {\n            // Transform 'time' from a string to a date\n            \"$addFields\": {\n                \"time\": {\n                    \"$dateFromString\": {\n                        \"dateString\": \"$time\"\n                    }\n                }\n            }\n        },\n        {\n            \"$match\": {\n                \"time\": {\n                    \"$gte\": new Date(\"${__from:date:iso}\"),\n                    \"$lte\": new Date(\"${__to:date:iso}\")\n                }\n            }\n        },\n        {\n            \"$sort\": {\n                \"time\": -1\n            }\n        },\n        // Project the fields we want to keep\n        {\n            \"$project\": {\n                \"_id\": \"$time\",\n                \"VWC\": 1,\n                \"VWC_RAW\":1,\n            }\n        }\n    ]\n    )",
     "type": "timeserie"
    }
   ]
  },
  { "title": "Weather Data for $target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }, "repeat": "target" },
  {
   "title": "Current (F)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "target": "db.weather_rack.aggregate(\n[\n    {\n        \"$match\": {\n            \"label\": \"${target}\",\n        }\n    },\n    {\n        \"$group\": {\n            \"_id\": \"$time\",\n            \"temp\": {\n                \"$avg\":\"$temperature\"\n            },\n            \"time\": {\n                \"$first\": \"$time\"\n            }\n        }\n    },\n    {\n        // Transform 'time' from a string to a date\n        \"$addFields\": {\n            \"time\": {\n                \"$dateFromString\": {\n                    \"dateString\": \"$time\"\n                }\n            }\n        }\n    },\n    {\n        \"$match\": {\n            \"time\": {\n                \"$gte\": new Date(\"${__from:date:iso}\"),\n                \"$lte\": new Date(\"${__to:date:iso}\")\n            }\n        }\n    },\n    {\n        \"$sort\": {\n            \"time\": -1\n        }\n    },\n    {\n        \"$addFields\": {\n        \"temperatureF\": {\n            \"$add\": [\n              { \"$multiply\": [ \"$temp\", 9/5 ] },\n              32\n            ]\n          }\n        }\n    },\n    // Project the fields we want to keep\n    {\n        \"$project\": {\n            \"_id\": 0,\n            \"temperatureF\": 1,\n            \"time\": 1,\n        }\n    }\n]\n)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Current (C)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "target": "db.weather_rack.aggregate(\n    [\n        {\n            \"$match\": {\n                \"label\": \"${target}\",\n            }\n        },\n        {\n            // Transform 'time' from a string to a date\n            \"$addFields\": {\n                \"time\": {\n                    \"$dateFromString\": {\n                        \"dateString\": \"$time\"\n                    }\n                }\n            }\n        },\n        {\n            \"$match\": {\n                \"time\": {\n                    \"$gte\": new Date(\"${__from:date:iso}\"),\n                    \"$lte\": new Date(\"${__to:date:iso}\")\n                }\n            }\n        },\n        {\n            \"$sort\": {\n                \"time\": -1\n            }\n        },\n        // Project the fields we want to keep\n        {\n            \"$project\": {\n                \"_id\": \"$time\",\n                \"temperature\": 1,\n            }\n        }\n    ]\n    )",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "target": "db.weather_rack.aggregate(\n[\n    {\n        \"$match\": {\n            \"label\": \"${target}\",\n        }\n    },\n    {\n        \"$group\": {\n            \"_id\": \"$time\",\n            \"time\": {\n                \"$first\": \"$time\"\n            },\n            \"humidity\": {\n                \"$avg\":\"$humidity\"\n            },\n        }\n    },\n    {\n        // Transform 'time' from a string to a date\n        \"$addFields\": {\n            \"time\": {\n                \"$dateFromString\": {\n                    \"dateString\": \"$time\"\n                }\n            }\n        }\n    },\n    {\n        \"$match\": {\n            \"time\": {\n                \"$gte\": new Date(\"${__from:date:iso}\"),\n                \"$lte\": new Date(\"${__to:date:iso}\")\n            }\n        }\n    },\n    {\n        \"$sort\": {\n            \"time\": -1\n        }\n    },\n    \n    // Project the fields we want to keep\n    {\n        \"$project\": {\n            \"_id\": 0,\n            \"time\": 1,\n            \"humidity\": 1,\n        }\n    }\n]\n)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Cumulative Rain",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "lengthin" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "target": "db.weather_rack.aggregate(\n    [\n        {\n            \"$match\": {\n                \"label\": \"${target}\",\n            }\n        },\n        {\n            \"$group\": {\n                \"_id\": \"$time\",\n                \"time\": {\n                    \"$first\": \"$time\"\n                },\n                \"rain\": {\n                    \"$avg\": \"$cumulativerain\"\n                },\n            }\n        },\n        {\n            // Transform 'time' from a string to a date\n            \"$addFields\": {\n                \"time\": {\n                    \"$dateFromString\": {\n                        \"dateString\": \"$time\"\n                    }\n                }\n            }\n        },\n        {\n            \"$match\": {\n                \"time\": {\n                    \"$gte\": new Date(\"${__from:date:iso}\"),\n                    \"$lte\": new Date(\"${__to:date:iso}\")\n                }\n            }\n        },\n        {\n            \"$sort\": {\n                \"time\": -1\n            }\n        },\n        {\n            \"$addFields\": {\n                \"rainIn\": {\n                    \"$divide\": [\"$rain\",25.4]\n                }\n            }\n        },\n        {\n            \"$limit\": 1\n        },\n        {\n            \"$project\": {\n                \"_id\": 0,\n                \"rainIn\": 1,\n            }\n        }\n    ])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Station: $target",
   "type": "text",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 13 },
   "options": {
    "content": "<img src=\"http://ec2-44-229-131-224.us-west-2.compute.amazonaws.com:8080/$target.jpg\" width=\"100%\">"
   }
  },
  {
   "title": "Battery",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "target": "db.weather_rack.aggregate(\n[\n    {\n        \"$match\": {\n            \"label\": \"${target}\",\n        }\n    },\n    {\n        \"$group\": {\n            \"_id\": \"$time\",\n            \"⚡\": {\n                \"$avg\":\"$batterylow\"\n            },\n            \"time\": {\n                \"$first\": \"$time\"\n            }\n        }\n    },\n    {\n        // Transform 'time' from a string to a date\n        \"$addFields\": {\n            \"time\": {\n                \"$dateFromString\": {\n                    \"dateString\": \"$time\"\n                }\n            }\n        }\n    },\n    {\n        \"$match\": {\n            \"time\": {\n                \"$gte\": new Date(\"${__from:date:iso}\"),\n                \"$lte\": new Date(\"${__to:date:iso}\")\n            }\n        }\n    },\n    {\n        \"$sort\": {\n            \"time\": -1\n        }\n    },\n    \n    // Project the fields we want to keep\n    {\n        \"$project\": {\n            \"_id\": 0,\n            \"time\": 1,\n            \"⚡\": \"$⚡\"\n        }\n    }\n]\n)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "target": "db.weather_rack.aggregate(\n[\n    {\n        \"$match\": {\n            \"label\": \"${target}\",\n        }\n    },\n    {\n        \"$group\": {\n            \"_id\": \"$time\",\n            \"time\": {\n                \"$first\": \"$time\"\n            },\n            \"windDir\": {\n                \"$avg\": \"$winddirection\"\n            },\n        }\n    },\n    {\n        // Transform 'time' from a string to a date\n        \"$addFields\": {\n            \"time\": {\n                \"$dateFromString\": {\n                    \"dateString\": \"$time\"\n                }\n            }\n        }\n    },\n    {\n        \"$match\": {\n            \"time\": {\n                \"$gte\": new Date(\"${__from:date:iso}\"),\n                \"$lte\": new Date(\"${__to:date:iso}\")\n            }\n        }\n    },\n    {\n        \"$sort\": {\n            \"time\": -1\n        }\n    },\n    {\n        \"$limit\": 1\n    },\n    {\n        \"$project\": {\n            \"_id\": 0,\n            \"windDir\": 1,\n        }\n    }\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "target": "db.weather_rack.aggregate(\n[\n    {\n        \"$match\": {\n            \"label\": \"${target}\",\n        }\n    },\n    {\n        \"$group\": {\n            \"_id\": \"$time\",\n            \"time\": {\n                \"$first\": \"$time\"\n            },\n            \"uv\": {\n                \"$avg\":\"$uv\"\n            },\n        }\n    },\n    {\n        // Transform 'time' from a string to a date\n        \"$addFields\": {\n            \"time\": {\n                \"$dateFromString\": {\n                    \"dateString\": \"$time\"\n                }\n            }\n        }\n    },\n    {\n        \"$match\": {\n            \"time\": {\n                \"$gte\": new Date(\"${__from:date:iso}\"),\n                \"$lte\": new Date(\"${__to:date:iso}\")\n            }\n        }\n    },\n    {\n        \"$sort\": {\n            \"time\": -1\n        }\n    },\n    \n    // Project the fields we want to keep\n    {\n        \"$project\": {\n            \"_id\": 0,\n            \"time\": 1,\n            \"uv\": 1,\n        }\n    }\n]\n)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Light",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "target": "db.weather_rack.aggregate(\n[\n    {\n        \"$match\": {\n            \"label\": \"${target}\",\n        }\n    },\n    {\n        \"$group\": {\n            \"_id\": \"$time\",\n            \"time\": {\n                \"$first\": \"$time\"\n            },\n            \"lux\": {\n                \"$avg\":\"$light\"\n            },\n        }\n    },\n    {\n        // Transform 'time' from a string to a date\n        \"$addFields\": {\n            \"time\": {\n                \"$dateFromString\": {\n                    \"dateString\": \"$time\"\n                }\n            }\n        }\n    },\n    {\n        \"$match\": {\n            \"time\": {\n                \"$gte\": new Date(\"${__from:date:iso}\"),\n                \"$lte\": new Date(\"${__to:date:iso}\")\n            }\n        }\n    },\n    {\n        \"$sort\": {\n            \"time\": -1\n        }\n    },\n    \n    // Project the fields we want to keep\n    {\n        \"$project\": {\n            \"_id\": 0,\n            \"time\": 1,\n            \"lux\": 1,\n        }\n    }\n]\n)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "$target Location",
   "type": "geomap",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "target": "db.weather_rack_instances.aggregate(\n[\n    {\n        \"$match\": {\n            \"instance_unique_identifier\": \"${target}\",\n        }\n    },\n]\n)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Average Windspeed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "target": "db.weather_rack.aggregate(\n    [\n        {\n            \"$match\": {\n                \"label\": \"${target}\",\n            }\n        },\n        {\n            \"$group\": {\n                \"_id\": \"$time\",\n                \"time\": {\n                    \"$first\": \"$time\"\n                },\n                \"wind\": {\n                    \"$avg\": \"$avewindspeed\"\n                },\n            }\n        },\n        {\n            // Transform 'time' from a string to a date\n            \"$addFields\": {\n                \"time\": {\n                    \"$dateFromString\": {\n                        \"dateString\": \"$time\"\n                    }\n                }\n            }\n        },\n        {\n            \"$match\": {\n                \"time\": {\n                    \"$gte\": new Date(\"${__from:date:iso}\"),\n                    \"$lte\": new Date(\"${__to:date:iso}\")\n                }\n            }\n        },\n        {\n            \"$sort\": {\n                \"time\": -1\n            }\n        },\n        {\n            \"$limit\": 1\n        },\n        {\n            $addFields: {\n              wind_mph: { $multiply: [ \"$wind\", 2.236936 ] }\n            }\n        },\n        {\n            \"$project\": {\n                \"_id\": 0,\n                \"wind_mph\": 1,\n            }\n        }\n    ])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Latest Wind Gust",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "target": "db.weather_rack.aggregate(\n        [\n            {\n                \"$match\": {\n                    \"label\": \"${target}\",\n                }\n            },\n            {\n                \"$group\": {\n                    \"_id\": \"$time\",\n                    \"time\": {\n                        \"$first\": \"$time\"\n                    },\n                    \"wind\": {\n                        \"$avg\": \"$gustwindspeed\"\n                    },\n                }\n            },\n            {\n                // Transform 'time' from a string to a date\n                \"$addFields\": {\n                    \"time\": {\n                        \"$dateFromString\": {\n                            \"dateString\": \"$time\"\n                        }\n                    }\n                }\n            },\n            {\n                \"$match\": {\n                    \"time\": {\n                        \"$gte\": new Date(\"${__from:date:iso}\"),\n                        \"$lte\": new Date(\"${__to:date:iso}\")\n                    }\n                }\n            },\n            {\n                \"$sort\": {\n                    \"time\": -1\n                }\n            },\n            {\n                \"$limit\": 1\n            },\n            {\n                $addFields: {\n                  wind_mph: { $multiply: [ \"$wind\", 2.236936 ] }\n                }\n            },\n            {\n                \"$project\": {\n                    \"_id\": 0,\n                    \"wind_mph\": 1,\n                }\n            }\n        ])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "pressurekpa" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "target": "db.bmp280.aggregate(\n    [\n        {\n            \"$group\": {\n                \"_id\": \"$time\",\n                \"time\": {\n                    \"$first\": \"$time\"\n                },\n                \"pressure\": {\n                    \"$avg\": \"$BarometricPressure\"\n                },\n            }\n        },\n        {\n            // Transform 'time' from a string to a date\n            \"$addFields\": {\n                \"time\": {\n                    \"$dateFromString\": {\n                        \"dateString\": \"$time\"\n                    }\n                }\n            }\n        },\n        {\n            \"$match\": {\n                \"time\": {\n                    \"$gte\": new Date(\"${__from:date:iso}\"),\n                    \"$lte\": new Date(\"${__to:date:iso}\")\n                }\n            }\n        },\n        {\n            \"$sort\": {\n                \"time\": -1\n            }\n        },\n        {\n            \"$limit\": 1\n        },\n        {\n            \"$project\": {\n                \"_id\": 0,\n                \"pressure\": 1,\n            }\n        }\n    ])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 23 },
   "options": {
    "content": "<img src=\"http://ec2-44-229-131-224.us-west-2.compute.amazonaws.com:8080/CSlogo.png\" width=\"100%\">\r\n<!--<img src=\"http://ec2-44-229-131-224.us-west-2.compute.amazonaws.com:8080/SCARECRO.png\" width=\"100%\">-->"
   }
  },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 23 },
   "options": {
    "content": "<!--<img src=\"http://ec2-44-229-131-224.us-west-2.compute.amazonaws.com:8080/CSlogo.png\" width=\"100%\">-->\r\n<img src=\"http://ec2-44-229-131-224.us-west-2.compute.amazonaws.com:8080/SCARECRO2.png\" width=\"100%\">"
   }
  },
  {
   "title": "Latest Reading",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "target": "db.weather_rack.aggregate(\n    [\n        {\n            \"$match\": {\n                \"label\": \"${target}\",\n            }\n        },\n        {\n            // Transform 'time' from a string to a date\n            \"$addFields\": {\n                \"time\": {\n                    \"$dateFromString\": {\n                        \"dateString\": \"$time\"\n                    }\n                }\n            }\n        },\n        {\n            \"$match\": {\n                \"time\": {\n                    \"$gte\": new Date(\"${__from:date:iso}\"),\n                    \"$lte\": new Date(\"${__to:date:iso}\")\n                }\n            }\n        },\n        {\n            \"$sort\": {\n                \"time\": -1\n            }\n        },\n        // Project the fields we want to keep\n        {\n            \"$project\": {\n                \"_id\": \"$time\",\n                \"time\": 1,\n            }\n        }\n    ]\n    )",
     "type": "timeserie"
    }
   ]
  },
  { "title": "Metric Measurements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Cumulative Rain",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "target": "db.weather_rack.aggregate(\n[\n    {\n        \"$match\": {\n            \"label\": \"${target}\",\n        }\n    },\n    {\n        \"$group\": {\n            \"_id\": \"$time\",\n            \"time\": {\n                \"$first\": \"$time\"\n            },\n            \"rain\": {\n                \"$avg\": \"$cumulativerain\"\n            },\n        }\n    },\n    {\n        // Transform 'time' from a string to a date\n        \"$addFields\": {\n            \"time\": {\n                \"$dateFromString\": {\n                    \"dateString\": \"$time\"\n                }\n            }\n        }\n    },\n    {\n        \"$match\": {\n            \"time\": {\n                \"$gte\": new Date(\"${__from:date:iso}\"),\n                \"$lte\": new Date(\"${__to:date:iso}\")\n            }\n        }\n    },\n    {\n        \"$sort\": {\n            \"time\": -1\n        }\n    },\n    {\n        \"$limit\": 1\n    },\n    {\n        \"$project\": {\n            \"_id\": 0,\n            \"rain\": 1,\n        }\n    }\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Average Windspeed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "target": "db.weather_rack.aggregate(\n[\n    {\n        \"$match\": {\n            \"label\": \"${target}\",\n        }\n    },\n    {\n        \"$group\": {\n            \"_id\": \"$time\",\n            \"time\": {\n                \"$first\": \"$time\"\n            },\n            \"wind\": {\n                \"$avg\": \"$avewindspeed\"\n            },\n        }\n    },\n    {\n        // Transform 'time' from a string to a date\n        \"$addFields\": {\n            \"time\": {\n                \"$dateFromString\": {\n                    \"dateString\": \"$time\"\n                }\n            }\n        }\n    },\n    {\n        \"$match\": {\n            \"time\": {\n                \"$gte\": new Date(\"${__from:date:iso}\"),\n                \"$lte\": new Date(\"${__to:date:iso}\")\n            }\n        }\n    },\n    {\n        \"$sort\": {\n            \"time\": -1\n        }\n    },\n    {\n        \"$limit\": 1\n    },\n    {\n        \"$project\": {\n            \"_id\": 0,\n            \"wind\": 1,\n        }\n    }\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Latest Wind Gust",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "target": "db.weather_rack.aggregate(\n[\n    {\n        \"$match\": {\n            \"label\": \"${target}\",\n        }\n    },\n    {\n        \"$group\": {\n            \"_id\": \"$time\",\n            \"time\": {\n                \"$first\": \"$time\"\n            },\n            \"wind\": {\n                \"$avg\": \"$gustwindspeed\"\n            },\n        }\n    },\n    {\n        // Transform 'time' from a string to a date\n        \"$addFields\": {\n            \"time\": {\n                \"$dateFromString\": {\n                    \"dateString\": \"$time\"\n                }\n            }\n        }\n    },\n    {\n        \"$match\": {\n            \"time\": {\n                \"$gte\": new Date(\"${__from:date:iso}\"),\n                \"$lte\": new Date(\"${__to:date:iso}\")\n            }\n        }\n    },\n    {\n        \"$sort\": {\n            \"time\": -1\n        }\n    },\n    {\n        \"$limit\": 1\n    },\n    {\n        \"$project\": {\n            \"_id\": 0,\n            \"wind\": 1,\n        }\n    }\n])",
     "type": "timeserie"
    }
   ]
  }
 ]
}