services:
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    user: '1000'
    ports:
      - 3000:3000
    volumes:
      - ./grafana-storage:/var/lib/grafana
      - ./mongodb-datasource:/var/lib/grafana/plugins/haohanyang-mongodb-datasource
    environment:
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: haohanyang-mongodb-datasource
